=== mskcc/ccs_cohort_utils/cohort_utils/schema/cohort-complete.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "cohort complete",
    "description": "Validate cohort complete NATS message",
    "type": "object",
    "properties": {
        "cohortId": {
            "type": "string",
            "description": "Cohort identifier"
        },
        "type":{
            "type": "string",
            "description": "Date of when the MAF analysis completed (YYYY-MM-DD)",
            "enum":["investigator","MSKWESRP","operational"]
        },
        "endUsers":{
            "type":"array",
            "description":"Analysts with access to the sample via cohorts",
            "items": {
                "type": "string"
            }
        },
        "pmUsers":{
            "type":"array",
            "description":"PMs managing the cohort",
            "items": {
                "type": "string"
            }
        },
        "projectTitle":{
            "type":"string",
            "description":"Project title"
        },
        "projectSubtitle":{
            "type":"string",
            "description":"Project subtitle"
        },
        "samples":{
            "type":"array",
            "description": "List of paired tumors in the cohort",
            "items": {
                "type": "object",
                "properties": {
                    "primaryId": {
                        "type":"string",
                        "description": "Stable tumor sample identifier",
                        "pattern": "^\\d{5}(?:_[A-Z]*)?(?:_\\d+){0,6}$"

                    },
                    "normalPrimaryId": {
                        "type":"string",
                        "description": "Stable normal sample identifier",
                        "pattern": "^\\d{5}(?:_[A-Z]*)?(?:_\\d+){0,6}$"
                    },
                    "cmoId":{
                        "type":"string",
                        "description":"Stable sample identifier of the normal sample"
                    },
                    "normalCmoId":{
                        "type":"string",
                        "description":"Stable sample identifier of the normal sample"
                    }
                },
                "anyOf": [
                    {
                        "required": ["primaryId","normalPrimaryId"]
                    },
                    {
                        "required": ["cmoId","normalCmoId"]
                    }
                ],
                "additionalProperties":false
            },
            "uniqueItems": true
        },
        "status": {
            "type": "string",
            "description": "Status of TEMPO workflow completion.",
            "enum": ["PASS","FAIL"]
        },
        "date": {
            "type": "string",
            "description": "Date of when the Cohort analysis completed (YYYY-MM-DD HH:MM)",
            "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01]) ([01][0-9]|2[0-3]):[0-5][0-9]$"
        },
        "pipelineVersion":{
            "type": "string",
            "description":"Version of the TEMPO pipeline"
        }
    },
    "required":["cohortId","date","type","samples","endUsers","pmUsers","status","projectTitle","pipelineVersion"],
    "additionalProperties":false
}

=== mskcc/ccs_cohort_utils/tests/data/json/cohort-complete.example.json
{
	"cohortId": "CCS_PPPQQQQ",
	"date": "2022-11-12 21:59",
	"type": "investigator",
	"pipelineVersion": "v2.0.x",
	"endUsers": ["noronhaa","gongy"],
        "pmUsers": ["raop","skicmopm"],
        "projectTitle":"A title",
        "projectSubtitle":"A longer description",
	"samples": [
                {"primaryId": "12345_A_3", "normalPrimaryId":"12345_A_4"},
                {"primaryId": "12345_A_5", "normalPrimaryId":"12345_A_6"},
                {"primaryId": "23456_B_3", "normalPrimaryId":"23456_B_4"},
                {"primaryId": "23456_B_3_1_1", "normalPrimaryId":"23456_B_4_1"},
                {"primaryId": "23456_3_1_1", "normalPrimaryId":"23456_4_1"}
        ],
        "status":"PASS"
}
