=== mskcc/ccs_cohort_utils/cohort_utils/schema/cohort-request.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "cohort request obj",
    "description": "Validate cohort complete NATS message",
    "type": "object",
    "properties": {
        "cohortId": {
            "type": "string",
            "description": "Cohort identifier"
        },
        "type":{
            "type": "string",
            "description": "Date of when the MAF analysis completed (YYYY-MM-DD)",
            "enum":["investigator","MSKWESRP","operational"]
        },
        "endUsers":{
            "type":"array",
            "description":"Analysts with access to the sample via cohorts",
            "items": {
                "type": "string"
            }
        },
        "pmUsers":{
            "type":"array",
            "description":"PMs managing the cohort",
            "items": {
                "type": "string"
            }
        },
        "projectTitle":{
            "type":"string",
            "description":"Project title"
        },
        "projectSubtitle":{
            "type":"string",
            "description":"Project subtitle"
        },
        "status":{
            "type":"string",
            "description":"Pipeline status",
            "enum":["PASS","FAIL","PROVISIONAL"]
        },
        "samples":{
            "type":"array",
            "description": "List of paired tumors in the cohort",
            "items": {
                "type": "object",
                "properties": {
                    "primaryId": {
                        "type":"string",
                        "description": "Stable tumor sample identifier",
                        "pattern": "^\\d{5}(?:_[A-Z]*)?(?:_\\d+){0,6}$"

                    },
                    "normalPrimaryId": {
                        "type":"string",
                        "description": "Stable normal sample identifier",
                        "pattern": "^\\d{5}(?:_[A-Z]*)?(?:_\\d+){0,6}$"
                    },
                    "cmoId": {
                        "type":"string",
                        "description": "Stable tumor sample identifier"
                    },
                    "normalCmoId": {
                        "type":"string",
                        "description": "Stable normal sample identifier"
                    },
		    "embargoDate": {
			"type":"string",
			"description": "Date on which the embargo expires (YYYY-MM-DD)",
			"pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
		    }
                },
                "anyOf": [
                    {
                        "required": ["primaryId"]
                    },
                    {
                        "required": ["cmoId"]
                    }
                ]
            },
            "uniqueItems": true
        }
    },
    "required":["cohortId","samples","endUsers","pmUsers","projectTitle"],
    "additionalProperties":false
}

=== mskcc/ccs_cohort_utils/tests/data/json/COHORT5.cohort.json
{
    "cohortId": "COHORT1",
    "endUsers": ["anoronh4", "enduser2"], 
    "pmUsers": ["pmuser1"], 
    "type": "investigator", 
    "projectTitle": "Genomic characterization of Responders", 
    "projectSubtitle": "Project_12345",
    "samples": [
        {"cmoId": "C-AAAAAA-P001-d", "normalCmoId": "C-AAAAAA-N001-d"},
        {"cmoId": "C-BBBBBB-P001-d", "normalCmoId": "C-BBBBBB-N001-d"}
    ]
}

=== mskcc/ccs_cohort_utils/tests/data/json/COHORT6.cohort.json
{
    "cohortId": "COHORT6",
    "endUsers": ["anoronh4", "enduser2"],
    "pmUsers": ["pmuser1"],
    "type": "investigator",
    "projectTitle": "Genomic characterization of Responders",
    "projectSubtitle": "Project_12345",
    "samples": [
        {"cmoId": "C-AAAAAA-P001-d", "normalCmoId": "C-AAAAAA-N001-d", "primaryId": "12345_A_1", "normalPrimaryId": "12345_A_2", "embargoDate": "2025-12-31"},
        {"cmoId": "C-BBBBBB-P001-d", "normalCmoId": "C-BBBBBB-N001-d", "primaryId": "12345_B_1", "normalPrimaryId": "12345_B_2", "embargoDate": "2026-06-30"},
        {"cmoId": "C-CCCCCC-P001-d", "normalCmoId": "C-CCCCCC-N001-d", "primaryId": "12345_C_1", "normalPrimaryId": "12345_C_2"},
	{"cmoId": "C-DDDDDD-P001-d", "embargoDate": "2026-06-30"},
	{"cmoId": "C-EEEEEE-T001-d"}
    ]
}

=== mskcc/ccs_cohort_utils/tests/data/json/COHORT3.cohort.json
{
    "cohortId": "COHORT3",
    "endUsers": ["anoronh4", "enduser2"], 
    "pmUsers": ["pmuser1"], 
    "type": "investigator", 
    "projectTitle": "Test SMILE metadata function", 
    "projectSubtitle": "NSCLC samples",
    "samples": [
        {"cmoId": "s_C_H5E30A_M005_d05", "normalCmoId": "s_C_H5E30A_N003_d03"}
    ]
}
